### ISSUE TITLE
Data Persistence?

### ISSUE THREAD

**Issue by domOrielton** [petercunha/Pad#3]
Not an issue, more of a question - any plans to add data persistence to Pad?  I think Pad is very good and it would be nice to add data persistence so the data stays between restarts. I'm not a Node.js programmer otherwise I would try it myself (maybe using https://github.com/simonlast/node-persist?). Does run very nicely on my own server though, thanks for your code.

**Comment by petercunha** [comment]
This is a good idea, I will consider implementing it in the future. Thanks!

**Comment by domOrielton** [comment]
Actually had a bit of time to get a working implementation of data persistence - as mentioned previously I'm not a Node.js programmer so it can definitely be improved on but it might be helpful to someone.

 I used 2 functions from [gregJS](https://www.gregjs.com/javascript/2016/checking-whether-a-file-directory-exists-without-using-fs-exists/) - isDirSync to check if a data directory was there and if not create it, and checkIfFile to check if the file exists if the pad data doesn't already exist (`if (pages.has(data.path))` returns false).  It should just be the socket.js file that needs to be changed (attached here as a .txt file) - any comments welcome.

Thanks again for original code, Dom
[socket.txt](https://github.com/petercunha/Pad/files/1594739/socket.txt)

**Comment by domOrielton** [comment]
I did think about updating/forking your code but I figured persistence might not be for everyone as saving data to the file system does create some risk - maybe I should have added a variable/flag that uses persistence if set... Happy to do that if the code is useful. Thanks, Dom
